spring:
  liquibase:
    changeLog: "classpath:db/changelog/changelog-master.yaml"
  zipkin:
    baseUrl: http://logs-aggregator:9411/
  sleuth:
    sampler:
      percentage: 1.0

server:
  error:
    whitelabel:
      enabled: false

management:
  server:
    port: 1111
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
    hostname: employee-api
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/





