spring:
  liquibase:
    changeLog: "classpath:db/changelog/changelog-master.yaml"
#  zipkin:
#    baseUrl: http://logs-aggregator:9411/
#  sleuth:
#    sampler:
#      percentage: 1.0

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'






