spring:
  liquibase:
    changeLog: "classpath:db/changelog/changelog-master.yaml"

server:
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/






