spring:
  liquibase:
    changeLog: "classpath:db/changelog/changelog-master.yaml"

server:
  error:
    whitelabel:
      enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false





