spring:
  application:
    name: service-registry

server:
  port: 8761
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
    hostname: service-registry
  client:
    register-with-eureka: false
    fetch-registry: false

