server:
  port: 0
  error:
    whitelabel:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}

spring:
  cloud:
    config:
      username: internal-app
      password: 1234
      uri:
        - http://localhost:8888



