version: "3"
services: 
  logs-aggregator:
    image: openzipkin/zipkin
    hostname: logs-aggregator
    ports:
      - "9411:9411"

  employee-api-db:
    image: postgres:12.2-alpine
    hostname: employee-api-db
    environment:
      POSTGRES_DB: "employees"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"

  smtp-server:
    build: 
      context: ./smtp_server
    hostname: smtp-server     
    entrypoint: "java -jar MockMock.jar"

  service-registry:
    build: 
      context: ./service_registry
    hostname: service-registry    
    entrypoint: "java -jar service_registry-1.0.jar"
    
  config-server:
    build: 
      context: ./config_server
    hostname: config-server  
    entrypoint: "java -jar config_server-1.0.jar"

  api-gateway:
    build: 
      context: ./api_gateway
    hostname: api-gateway 
    restart: on-failure       
    ports:
      - "9000:9000"  
    entrypoint: "java -jar api_gateway-1.0.jar"
    depends_on:
      - service-registry
      - logs-aggregator      

  currency-conversion-api:
    build: 
      context: ./currency_conversion_api
    hostname: currency-conversion-api
    restart: on-failure
    entrypoint: "java -jar -Dspring.profiles.active=dev currency_conversion_api-1.0.jar"
    depends_on:      
      - config-server
      - api-gateway
    
  employee-api:
    build: 
      context: ./employee_api
    hostname: employee-api
    restart: on-failure
    entrypoint: "java -jar -Dspring.profiles.active=dev employee_api-1.0.jar"
    depends_on:      
      - employee-api-db
      - smtp-server      
      - currency-conversion-api
    
  monitoring-server:
    build: 
      context: ./monitoring_server
    hostname: monitoring-server     
    ports:
      - "9090:9090" 
    depends_on:   
      - employee-api     




      