apiVersion: v1
kind: Service
metadata:
  name: employee-api-db
spec:
  # type: NodePort
  selector:
    app: employee-api-db
  ports:
    - #nodePort: 30000
      port: 5432
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-api-db
  template:
    metadata:
      labels:
        app: employee-api-db
    spec:
      containers:
        - name: employee-api-db
          image: postgres:12.2-alpine
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: employees
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: root

      
  
