server:
  port: 9000
  error:
    whitelabel:
      enabled: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 6000

zuul:
  ignored-services:
    - '*'
  routes:
    currency-conversion-api:
      path: /currency-conversion-api/**
      serviceId: currency-conversion-api
    employee-api:
      path: /employee-api/**
      serviceId: employee-api