spring:
  datasource:
    url: jdbc:postgresql://${EMPLOYEE_API_DB_SERVICE_HOST}:5432/employees
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${SMTP_SERVER_SERVICE_HOST}
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

chunk-size: 50

via:
  default-email:
    sender: no-reply@via.com
    subject: 'Scheduled rate alerts'
  scheduled-email:
    rate: '0 * * * * ?'

logging:
  level:
    root: info
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'