apiVersion: v1
kind: Service
metadata:
  name: currency-conversion-api
  labels:
    app: currency-conversion-api
spec:
  selector:
    app: currency-conversion-api
  ports:
    - port: 8080
      name: http-traffic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion-api
  labels:
    app: currency-conversion-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-conversion-api
  template:
    metadata:
      labels:
        app: currency-conversion-api
    spec:
      containers:
        - name: currency-conversion-api
          image: currency-conversion-api:1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: currency-conversion-api          
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60  
            periodSeconds: 30
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: currency-conversion-api-monitor
spec:
  selector:
    matchLabels:
      app: currency-conversion-api
  endpoints:
  - port: http-traffic
    path: /actuator/prometheus