#spring:
#  zipkin:
#    baseUrl: http://logs-aggregator:9411/
#  sleuth:
#    sampler:
#      percentage: 1.0

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'





