external:
  api:
    countries: https://restcountries.eu/rest/v2
    rates: https://api.exchangeratesapi.io/latest

spring:
  application:
    name: currency-conversion-api
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
      config:
        enabled: false
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

server:
  port: 8580
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: info
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'