spring:
  zipkin:
    baseUrl: http://logs-aggregator:9411/
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    prefer-ip-address: true
    hostname: currency-conversion-api
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/






