server:
  port: 8888
  error:
    whitelabel:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}

spring:
  profiles:
    active: native
